# Generated by Django 3.1 on 2021-01-13 17:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical_assistant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipoUsuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='TipoUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medical_assistant.tipousuario'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='Fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 13, 37, 16, 321198)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='FechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 17, 37, 16, 317188, tzinfo=utc)),
        ),
    ]
