# Generated by Django 3.1 on 2020-12-23 18:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='TipoUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medical_assistant.tipousuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='FechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 18, 19, 9, 640511, tzinfo=utc)),
        ),
    ]
