# Generated by Django 3.1 on 2021-01-13 18:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical_assistant', '0003_auto_20210113_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='TipoUsuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medical_assistant.tipousuario'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='Fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 14, 43, 43, 934610)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='FechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 18, 43, 43, 930609, tzinfo=utc)),
        ),
    ]
