# Generated by Django 3.1 on 2021-01-07 20:12

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical_assistant', '0004_auto_20201223_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='TipoUsuario',
            new_name='tipoUsuario',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='CedulaTutor',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 11', regex='^.{11}$')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='NombreTutor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subespecialidad',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subespecialidades', to='medical_assistant.especialidad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='FechaNacimiento',
            field=models.DateField(default=datetime.date(2021, 1, 7)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='FechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 20, 12, 20, 94196, tzinfo=utc)),
        ),
    ]
