# Generated by Django 3.1 on 2021-01-13 23:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical_assistant', '0005_auto_20210113_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='Fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 19, 24, 37, 109469)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='FechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 23, 24, 37, 104967, tzinfo=utc)),
        ),
    ]
